version: '2'
services:
  postgres:
    restart: on-failure:10
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=xonotic
      - POSTGRES_USER=xonotic
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  api:
    build:
      context: build
      dockerfile: api.Dockerfile
    environment:
      - VIRTUAL_HOST=api.xmr.local
      - PGPASSWORD=password
    links:
      - postgres
  web:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - api
    ports:
      - 80:80