version: '2'
services:
    postgres:
        restart: on-failure:10
        image: postgres:9.4
    memcached:
        image: memcached
    app_api:
        build:
            context: .
            dockerfile: docker/containers/app_api.Dockerfile
# These are alternative ways to connect without having to rebuild the image
#        command: /bin/wait-for-postgres.sh postgres xmra-serve
#        command: /bin/bash -c "/bin/wait-for-postgres.sh postgres xmra-init; xmra-serve"
        command: /bin/bash -c "/bin/wait-for-postgres.sh postgres xmra-init; xmra-add --all; xmra-serve"
#        command: /bin/bash -c "/bin/wait-for-postgres.sh postgres gunicorn -b '0.0.0.0:80' --reload xmra.app:api"
        links:
            - postgres
    nginx_proxy:
        build:
            context: .
            dockerfile: docker/containers/nginx_proxy.Dockerfile
        command: /bin/wait-for-api.sh