version: '2'
services:
  postgres:
    restart: on-failure:10
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=xonotic
      - POSTGRES_USER=xonotic
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  api:
    build:
      context: build
      dockerfile: api.Dockerfile
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=api.xonotic-repo.local
      - PGPASSWORD=password
    command: /bin/wait-for-postgres.sh postgres xmra-serve
#    command: /bin/bash -c "/bin/wait-for-postgres.sh postgres xmra-init; xmra-serve"
#    command: /bin/bash -c "/bin/wait-for-postgres.sh postgres gunicorn -b '0.0.0.0:80' --reload xmra.app:api"
    links:
      - postgres
  web:
    build:
      context: build
      dockerfile: web.Dockerfile
    environment:
      - DEFAULT_HOST=www.xonotic-repo.local
    ports:
      - "80:80"
    volumes:
      - ./build/nginx/conf:/etc/nginx/conf.d:rw
      - ./build/nginx/vhost:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
